import {
  db,
  pool,
  brandsTable,
  departmentsTable,
  projectsTable,
  predictorsTable,
  decisionsTable,
  decisionNotesTable,
  executiveSummaryTable,
  reviewersTable,
} from "@workspace/db";

// Idempotent seed for the CAG parent-company expansion. Re-running fully
// replaces brands, departments, projects, predictors, decisions and the
// executive summary singleton. Other tables (financial, risk, roadmap,
// strategy, sources, guardrails, reviews) are left untouched.

const AUTH = {
  view: "View only",
  review: "Review",
  recommend: "Recommend",
  rose: "Needs Rose approval",
  carmen: "Needs Carmen systems review",
  tony: "Needs Tony founder review",
  both: "Needs both founder approval",
  written: "Requires written approval",
} as const;

const brands = [
  {
    code: "CAG",
    name: "CAG",
    fullName: "Compliance Authority Group",
    kind: "parent",
    parentCode: null,
    stage: "Active",
    health: 86,
    risk: "Low",
    tagline: "Parent holding company",
    summary:
      "Parent company overseeing the compliance authority brand portfolio. One active operating brand (CCA) with four candidate brands in concept and planning.",
    authorityLabel: AUTH.view,
    sort: 0,
  },
  {
    code: "CCA",
    name: "CCA",
    fullName: "Contractor Compliance Authority",
    kind: "brand",
    parentCode: "CAG",
    stage: "Active",
    health: 84,
    risk: "Medium",
    tagline: "Active operating brand",
    summary:
      "The only active, revenue-generating brand. Eight operating departments under founder-level oversight. Carries the portfolio today.",
    authorityLabel: AUTH.review,
    sort: 1,
  },
  {
    code: "PCA",
    name: "PCA",
    fullName: "Professional Compliance Authority",
    kind: "brand",
    parentCode: "CAG",
    stage: "Build Concept",
    health: 62,
    risk: "Medium",
    tagline: "Candidate brand",
    summary:
      "Lead candidate brand. Build phase concept under evaluation; launch readiness tracking at 72%. Pending founder review before any commitment.",
    authorityLabel: AUTH.tony,
    sort: 2,
  },
  {
    code: "QCA",
    name: "QCA",
    fullName: "Quality Compliance Authority",
    kind: "brand",
    parentCode: "CAG",
    stage: "Planned",
    health: 48,
    risk: "Medium",
    tagline: "Candidate brand",
    summary:
      "Planned candidate brand. Early market and model definition only. No capital committed; visibility-only.",
    authorityLabel: AUTH.review,
    sort: 3,
  },
  {
    code: "CANNACA",
    name: "CANNA CA",
    fullName: "Cannabis Compliance Authority",
    kind: "brand",
    parentCode: "CAG",
    stage: "Future",
    health: 38,
    risk: "High",
    tagline: "Candidate brand",
    summary:
      "Future candidate brand in a high-regulation vertical. Concept only — elevated legal and CLP separation considerations. No action authorized.",
    authorityLabel: AUTH.written,
    sort: 4,
  },
  {
    code: "GCA",
    name: "GCA",
    fullName: "Government Compliance Authority",
    kind: "brand",
    parentCode: "CAG",
    stage: "Future",
    health: 41,
    risk: "Medium",
    tagline: "Candidate brand",
    summary:
      "Future candidate brand targeting public-sector compliance. Concept stage; long-horizon, founder review required before scoping.",
    authorityLabel: AUTH.tony,
    sort: 5,
  },
];

const departments = [
  {
    brandCode: "CCA",
    name: "Sales & Enrollment",
    status: "On Track",
    health: 82,
    blockers: 0,
    nextAction: "Hold Q3 pipeline review",
    owner: "Sales Lead",
    summary: "New enrollment volume steady; conversion holding at 31%.",
    authorityLabel: AUTH.review,
    sort: 0,
  },
  {
    brandCode: "CCA",
    name: "Client Fulfillment",
    status: "At Risk",
    health: 58,
    blockers: 2,
    nextAction: "Add fulfillment capacity",
    owner: "Operations Lead",
    summary: "Utilization at 92%; capacity is the binding constraint.",
    authorityLabel: AUTH.recommend,
    sort: 1,
  },
  {
    brandCode: "CCA",
    name: "Application Processing",
    status: "At Risk",
    health: 54,
    blockers: 3,
    nextAction: "Clear aged application backlog",
    owner: "Processing Lead",
    summary: "Seven applications past target turnaround.",
    authorityLabel: AUTH.recommend,
    sort: 2,
  },
  {
    brandCode: "CCA",
    name: "Document Collection",
    status: "On Track",
    health: 71,
    blockers: 1,
    nextAction: "Follow up on 14 open requests",
    owner: "Records Lead",
    summary: "Open document requests trending down week over week.",
    authorityLabel: AUTH.review,
    sort: 3,
  },
  {
    brandCode: "CCA",
    name: "Finance & Reserve",
    status: "On Track",
    health: 78,
    blockers: 0,
    nextAction: "Confirm reserve runway model",
    owner: "Finance Lead",
    summary: "Reserve runway at 5.7 months against a 6-month target.",
    authorityLabel: AUTH.tony,
    sort: 4,
  },
  {
    brandCode: "CCA",
    name: "Technology & AI",
    status: "On Track",
    health: 80,
    blockers: 0,
    nextAction: "Advance platform roadmap phase 2",
    owner: "Platform Lead",
    summary: "AI initiatives returning an estimated 2.4x on effort.",
    authorityLabel: AUTH.carmen,
    sort: 5,
  },
  {
    brandCode: "CCA",
    name: "Compliance & Legal",
    status: "On Track",
    health: 76,
    blockers: 1,
    nextAction: "Review CLP separation controls",
    owner: "Compliance Lead",
    summary: "CLP separation guardrails enforced; one item under watch.",
    authorityLabel: AUTH.written,
    sort: 6,
  },
  {
    brandCode: "CCA",
    name: "People & Workload",
    status: "At Risk",
    health: 55,
    blockers: 2,
    nextAction: "Rebalance overloaded roles",
    owner: "People Lead",
    summary: "Three roles flagged overloaded; knowledge gaps moderate.",
    authorityLabel: AUTH.rose,
    sort: 7,
  },
];

const projects = [
  {
    brandCode: "CCA",
    department: "Technology & AI",
    name: "AI Document Intake Automation",
    status: "in_progress",
    health: 74,
    owner: "Platform Lead",
    summary: "Automating document classification to cut intake time.",
    dueDate: "2026-08-15",
    authorityLabel: AUTH.carmen,
    sourceRecord: "Platform Roadmap Phase 2",
    sort: 0,
  },
  {
    brandCode: "CCA",
    department: "Client Fulfillment",
    name: "Fulfillment Capacity Expansion",
    status: "at_risk",
    health: 52,
    owner: "Operations Lead",
    summary: "Adding capacity to relieve 92% utilization constraint.",
    dueDate: "2026-07-30",
    authorityLabel: AUTH.recommend,
    sourceRecord: "Operations Capacity Plan",
    sort: 1,
  },
  {
    brandCode: "CCA",
    department: "Application Processing",
    name: "Backlog Clearance Sprint",
    status: "at_risk",
    health: 49,
    owner: "Processing Lead",
    summary: "Clearing aged applications past target turnaround.",
    dueDate: "2026-07-10",
    authorityLabel: AUTH.recommend,
    sourceRecord: "Processing Backlog Report",
    sort: 2,
  },
  {
    brandCode: "CCA",
    department: "Finance & Reserve",
    name: "Operating Reserve Model Refresh",
    status: "in_progress",
    health: 70,
    owner: "Finance Lead",
    summary: "Updating reserve runway model and revenue trigger logic.",
    dueDate: "2026-08-01",
    authorityLabel: AUTH.tony,
    sourceRecord: "Monthly Founder Review",
    sort: 3,
  },
  {
    brandCode: "PCA",
    department: null,
    name: "PCA Brand Launch Readiness",
    status: "planned",
    health: 66,
    owner: "Strategy Lead",
    summary: "Launch readiness assessment for the PCA candidate brand.",
    dueDate: "2026-09-30",
    authorityLabel: AUTH.tony,
    sourceRecord: "Brand Concept Brief",
    sort: 4,
  },
  {
    brandCode: "CCA",
    department: "People & Workload",
    name: "Workload Rebalancing Plan",
    status: "in_progress",
    health: 57,
    owner: "People Lead",
    summary: "Rebalancing three overloaded roles and closing knowledge gaps.",
    dueDate: "2026-07-20",
    authorityLabel: AUTH.rose,
    sourceRecord: "People Capacity Review",
    sort: 5,
  },
];

const predictors = [
  {
    key: "revenue_forecast",
    name: "Revenue Forecast",
    category: "Financial",
    level: "On Track",
    value: "$3.4M Q3",
    trend: "up",
    score: 82,
    summary: "Forward revenue tracking ahead of plan.",
    detail:
      "Projected Q3 retained revenue of $3.4M, modestly ahead of the operating plan based on current pipeline conversion.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.review,
    sort: 0,
  },
  {
    key: "collected_retained_revenue",
    name: "Collected Retained Revenue",
    category: "Financial",
    level: "On Track",
    value: "$27.6M",
    trend: "up",
    score: 88,
    summary: "Cumulative collected and retained revenue.",
    detail: "Total collected retained revenue across CCA, the basis for reserve and runway calculations.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.view,
    sort: 1,
  },
  {
    key: "operating_reserve_runway",
    name: "Operating Reserve Runway",
    category: "Financial",
    level: "Moderate",
    value: "5.7 mo",
    trend: "flat",
    score: 64,
    summary: "Months of runway at current burn.",
    detail: "Reserve runway is 5.7 months against a 6-month target; watch but not action-needed.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.tony,
    sort: 2,
  },
  {
    key: "cash_timing",
    name: "Cash Timing Risk",
    category: "Financial",
    level: "Elevated",
    value: "12 days",
    trend: "down",
    score: 48,
    summary: "Timing gap between collections and obligations.",
    detail: "Average 12-day gap between receivable timing and major obligations; elevated relative to target.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.recommend,
    sort: 3,
  },
  {
    key: "pipeline_conversion",
    name: "Sales Pipeline Conversion",
    category: "Operational",
    level: "Moderate",
    value: "31%",
    trend: "flat",
    score: 61,
    summary: "Lead-to-enrollment conversion rate.",
    detail: "Conversion holding at 31%; stable but below the stretch target.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.review,
    sort: 4,
  },
  {
    key: "client_risk",
    name: "Client Risk",
    category: "Risk",
    level: "Moderate",
    value: "6 accounts",
    trend: "flat",
    score: 58,
    summary: "Accounts flagged for retention or compliance risk.",
    detail: "Six client accounts carry elevated retention or compliance risk and warrant monitoring.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.review,
    sort: 5,
  },
  {
    key: "fulfillment_capacity",
    name: "Fulfillment Capacity",
    category: "Operational",
    level: "At Risk",
    value: "92% util",
    trend: "down",
    score: 42,
    summary: "Fulfillment utilization vs available capacity.",
    detail: "Fulfillment is running at 92% utilization, the binding operational constraint this quarter.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.recommend,
    sort: 6,
  },
  {
    key: "application_delay",
    name: "Application Delay Risk",
    category: "Operational",
    level: "Elevated",
    value: "7 apps",
    trend: "down",
    score: 45,
    summary: "Applications past target turnaround.",
    detail: "Seven applications are past target turnaround time, concentrated in processing.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.recommend,
    sort: 7,
  },
  {
    key: "document_collection",
    name: "Document Collection Risk",
    category: "Operational",
    level: "Moderate",
    value: "14 open",
    trend: "down",
    score: 60,
    summary: "Open outstanding document requests.",
    detail: "Fourteen open document requests; trending down week over week.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.review,
    sort: 8,
  },
  {
    key: "decision_delay",
    name: "Decision Delay",
    category: "Operational",
    level: "Moderate",
    value: "3 stalled",
    trend: "flat",
    score: 57,
    summary: "Decisions awaiting movement.",
    detail: "Three major decisions are stalled awaiting founder review or supporting source records.",
    brandCode: null,
    onRadar: false,
    authorityLabel: AUTH.tony,
    sort: 9,
  },
  {
    key: "decision_threshold_alerts",
    name: "Major Decision Threshold Alerts",
    category: "Risk",
    level: "High",
    value: "2 over",
    trend: "up",
    score: 38,
    summary: "Decisions exceeding authority thresholds.",
    detail: "Two pending items exceed budget or authority thresholds and require written approval.",
    brandCode: null,
    onRadar: true,
    authorityLabel: AUTH.written,
    sort: 10,
  },
  {
    key: "tech_ai_roi",
    name: "Technology / AI ROI",
    category: "Strategic",
    level: "On Track",
    value: "2.4x",
    trend: "up",
    score: 78,
    summary: "Return on technology and AI initiatives.",
    detail: "Platform and AI initiatives returning an estimated 2.4x on invested effort.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.carmen,
    sort: 11,
  },
  {
    key: "brand_launch_readiness",
    name: "Brand Launch Readiness",
    category: "Strategic",
    level: "Moderate",
    value: "PCA 72%",
    trend: "up",
    score: 66,
    summary: "Candidate brand launch readiness.",
    detail: "PCA candidate brand at 72% launch readiness; remaining candidates earlier in concept.",
    brandCode: "PCA",
    onRadar: false,
    authorityLabel: AUTH.tony,
    sort: 12,
  },
  {
    key: "team_workload",
    name: "Team Workload",
    category: "People",
    level: "Elevated",
    value: "3 overloaded",
    trend: "up",
    score: 44,
    summary: "Roles flagged as overloaded.",
    detail: "Three roles are flagged overloaded, concentrated in fulfillment and processing.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.rose,
    sort: 13,
  },
  {
    key: "knowledge_gaps",
    name: "Knowledge Gaps",
    category: "People",
    level: "Moderate",
    value: "Moderate",
    trend: "flat",
    score: 59,
    summary: "Single-point-of-knowledge exposure.",
    detail: "Moderate concentration of knowledge in single individuals; documentation in progress.",
    brandCode: "CCA",
    onRadar: true,
    authorityLabel: AUTH.review,
    sort: 14,
  },
  {
    key: "duplicate_work",
    name: "Duplicate Work Risk",
    category: "People",
    level: "Low",
    value: "Low",
    trend: "flat",
    score: 80,
    summary: "Redundant effort across teams.",
    detail: "Low duplicate-work risk; departmental ownership is well separated.",
    brandCode: "CCA",
    onRadar: false,
    authorityLabel: AUTH.view,
    sort: 15,
  },
  {
    key: "clp_separation_risk",
    name: "Legal / CLP Separation Risk",
    category: "Risk",
    level: "Elevated",
    value: "Elevated",
    trend: "flat",
    score: 47,
    summary: "CLP separation and authority exposure.",
    detail:
      "CLP separation must be preserved across brands; candidate brands in regulated verticals raise this exposure.",
    brandCode: null,
    onRadar: true,
    authorityLabel: AUTH.written,
    sort: 16,
  },
  {
    key: "strategic_opportunities",
    name: "Strategic Opportunities",
    category: "Strategic",
    level: "Strong",
    value: "High",
    trend: "up",
    score: 85,
    summary: "Identified upside opportunities.",
    detail: "Strong slate of strategic opportunities across brand expansion and platform leverage.",
    brandCode: null,
    onRadar: true,
    authorityLabel: AUTH.recommend,
    sort: 17,
  },
];

const decisions = [
  {
    title: "PCA Brand Build Phase Approval",
    description:
      "Authorize the build phase for the PCA candidate brand, including initial scoping and team allocation.",
    category: "Brand Strategy",
    approvalType: "strategic",
    estimatedImpact: "$1.2M",
    dueDate: "2026-07-15",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Recommend proceeding to scoped build phase pending budget confirmation.",
    sourceRecord: "Brand Concept Brief",
    authorityLabel: AUTH.tony,
    brandCode: "PCA",
    sort: 0,
  },
  {
    title: "CCA Pricing Model Update",
    description: "Update CCA enrollment pricing tiers to reflect fulfillment cost changes.",
    category: "Financial Commitment",
    approvalType: "financial_commitment",
    estimatedImpact: "$640K",
    dueDate: "2026-07-08",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Recommend phased rollout with grandfathering for existing clients.",
    sourceRecord: "Finance Pricing Analysis",
    authorityLabel: AUTH.both,
    brandCode: "CCA",
    sort: 1,
  },
  {
    title: "Fulfillment Capacity Expansion",
    description: "Add fulfillment capacity to relieve the 92% utilization constraint.",
    category: "Operations",
    approvalType: "budget_threshold",
    estimatedImpact: "$480K",
    dueDate: "2026-07-22",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Recommend approval; constraint is limiting revenue throughput.",
    sourceRecord: "Operations Capacity Plan",
    authorityLabel: AUTH.tony,
    brandCode: "CCA",
    sort: 2,
  },
  {
    title: "CLP System Integration",
    description: "Integrate a new compliance system while preserving CLP separation controls.",
    category: "Platform / Systems",
    approvalType: "ip_platform_rights",
    estimatedImpact: "$310K",
    dueDate: "2026-08-01",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Requires Carmen systems review before any commitment.",
    sourceRecord: "Platform Roadmap Phase 2",
    authorityLabel: AUTH.carmen,
    brandCode: "CCA",
    sort: 3,
  },
  {
    title: "FY26 Operating Budget Approval",
    description: "Approve the consolidated FY26 operating budget across the CAG portfolio.",
    category: "Financial Commitment",
    approvalType: "needs_written_approval",
    estimatedImpact: "$5.4M",
    dueDate: "2026-07-31",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Requires written founder approval; exceeds standing budget authority.",
    sourceRecord: "Monthly Founder Review",
    authorityLabel: AUTH.written,
    brandCode: "CAG",
    sort: 4,
  },
  {
    title: "Audit Risk Threshold Update",
    description: "Adjust the audit risk threshold that triggers founder review.",
    category: "Risk Governance",
    approvalType: "strategic",
    estimatedImpact: "$120K",
    dueDate: "2026-07-18",
    status: "pending",
    founderApprovalRequired: true,
    recommendation: "Recommend a tighter threshold given elevated decision alerts.",
    sourceRecord: "Risk Register",
    authorityLabel: AUTH.review,
    brandCode: "CAG",
    sort: 5,
  },
  {
    title: "CANNA CA Concept Evaluation",
    description: "Authorize an evaluation of the CANNA CA candidate brand concept.",
    category: "Brand Strategy",
    approvalType: "strategic",
    estimatedImpact: "$90K",
    dueDate: "2026-09-01",
    status: "deferred",
    founderApprovalRequired: true,
    recommendation: "Defer pending legal review of CLP separation in regulated vertical.",
    sourceRecord: "Brand Concept Brief",
    authorityLabel: AUTH.written,
    brandCode: "CANNACA",
    sort: 6,
  },
  {
    title: "Application Processing Backlog Sprint",
    description: "Fund a focused sprint to clear the aged application backlog.",
    category: "Operations",
    approvalType: "budget_threshold",
    estimatedImpact: "$75K",
    dueDate: "2026-07-05",
    status: "approved",
    founderApprovalRequired: false,
    recommendation: "Approved within standing operational authority.",
    sourceRecord: "Processing Backlog Report",
    authorityLabel: AUTH.recommend,
    brandCode: "CCA",
    sort: 7,
  },
];

const executiveSummary = {
  companyPulse: {
    label: "CAG Portfolio Health",
    value: "86",
    unit: "/100",
    change: "+2",
    trend: "up",
    helper: "Parent portfolio composite",
  },
  collectedRetainedRevenue: {
    label: "Collected Retained Revenue",
    value: "$27.6M",
    unit: null,
    change: "+4.1%",
    trend: "up",
    helper: "Cumulative across CCA",
  },
  operatingReserve: {
    label: "Operating Reserve Runway",
    value: "5.7",
    unit: "mo",
    change: "-0.2",
    trend: "down",
    helper: "Target 6.0 months",
  },
  majorDecisionsPending: {
    label: "Major Decisions Pending",
    value: "7",
    unit: null,
    change: "+2",
    trend: "down",
    helper: "Awaiting founder review",
  },
  predictiveAlerts: {
    label: "Predictive Alerts",
    value: "14",
    unit: null,
    change: "+3",
    trend: "down",
    helper: "Across 18 intelligence modules",
  },
  pulseTrend: [78, 80, 79, 82, 81, 83, 84, 86],
};

const reviewers = [
  { name: "Tony Casella", sort: 0 },
  { name: "Carmen Vega", sort: 1 },
  { name: "Rose Delacroix", sort: 2 },
];

async function seed() {
  await db.transaction(async (tx) => {
    await tx.delete(brandsTable);
    await tx.delete(departmentsTable);
    await tx.delete(projectsTable);
    await tx.delete(predictorsTable);
    await tx.delete(decisionNotesTable);
    await tx.delete(decisionsTable);
    await tx.delete(executiveSummaryTable);
    await tx.delete(reviewersTable);

    await tx.insert(brandsTable).values(brands);
    await tx.insert(departmentsTable).values(departments);
    await tx.insert(projectsTable).values(projects);
    await tx.insert(predictorsTable).values(predictors);
    await tx.insert(decisionsTable).values(decisions);
    await tx.insert(executiveSummaryTable).values(executiveSummary);
    await tx.insert(reviewersTable).values(reviewers);
  });

  console.log("Seeded CAG cockpit data:");
  console.log(`  brands: ${brands.length}`);
  console.log(`  departments: ${departments.length}`);
  console.log(`  projects: ${projects.length}`);
  console.log(`  predictors: ${predictors.length}`);
  console.log(`  decisions: ${decisions.length}`);
  console.log(`  executive summary: 1`);
  console.log(`  reviewers: ${reviewers.length}`);
}

seed()
  .then(() => pool.end())
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed failed:", err);
    return pool.end().finally(() => process.exit(1));
  });
